library(arules)
library(arulesViz)
book <- read.csv(file.choose())
View(book)
(book1 <- apriori(as.matrix(book),parameter = list(support=0.03,confidence=0.6,minlen=2)))
book1 <- apriori(as.matrix(book),parameter = list(support=0.03,confidence=0.65,minlen=2))
book1 <- apriori(as.matrix(book),parameter = list(support=0.03,confidence=0.67,minlen=2))
book1 <- apriori(as.matrix(book),parameter = list(support=0.03,confidence=0.68,minlen=2))
book1 <- apriori(as.matrix(book),parameter = list(suppor=0.035,confidence=0.69,minlen=2))
inspect(book1)
inspect(book1,by="lift")
inspect(sort(book1,by="lift"))
inspect(head(sort(book1,by="lift")))
head(quality(sort(book1,by="lift")))
plot(book1)
windows()
plot(book1,method = "grouped")
plot(book1,method = "graph")
plot(book1[1:20],method = "graph")
write(book1,file = "books_result.csv")
getwd()
